# Generated by Django 5.2 on 2025-04-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('first_names', models.CharField(max_length=100)),
                ('last_names', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('document_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.documentimage')),
            ],
        ),
    ]
